input {
  # Đọc file log JSON Lines từ Nginx
  file {
    path => "/var/log/nginx/access_json.log"
    start_position => "beginning"
    #sincedb_path => "/dev/null" # Chỉ dùng cho môi trường dev để luôn đọc lại từ đầu
    codec => "json"
  }
}

filter {
  # 1. Đảm bảo cấu trúc chuẩn
  if [schema] != "v1" {
    drop { } # Bỏ qua các dòng log rác không đúng schema
  }

  # 2. PATH NORMALIZATION 
  mutate {
    gsub => [
      # Xóa dấu slash dư thừa ở cuối (VD: /api/cart/ -> /api/cart)
      "path_normalized", "/$", "",
      
      # Thay thế UUID (dành cho các hệ thống dùng UUID làm khóa chính)
      "path_normalized", "/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}", "/{uuid}",
      
      # Thay thế Email (VD: /api/users/by-email/admin@test.com -> /api/users/by-email/{email})
      "path_normalized", "/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", "/{email}",
      
      # Thay thế các con số ID (VD: /api/products/123 -> /api/products/{id})
      "path_normalized", "/[0-9]+", "/{id}"
    ]
  }

  # 3. CHUYỂN ĐỔI KIỂU DỮ LIỆU (Type Casting)
  # Nginx trả request_time bằng giây (VD: "1.226"). Ta đổi thành số thực (float).
  mutate {
    convert => {
      "status" => "integer"
      "response_size" => "integer"
      "response_time_ms" => "float"
      "sampling_flag" => "integer"
    }
  }

  # Đổi ra mili-giây (ms) thực sự cho biến response_time_ms
  ruby {
    code => "
      if event.get('response_time_ms')
        event.set('response_time_ms', (event.get('response_time_ms') * 1000).to_i)
      end
    "
  }

  # 4. CHUẨN HÓA THỜI GIAN
  # Lấy trường "timestamp" của Nginx làm thời gian thực tế (@timestamp) của Elasticsearch
  date {
    match => [ "timestamp", "ISO8601" ]
    target => "@timestamp"
    remove_field => [ "timestamp" ] # Xóa trường cũ để tránh trùng lặp
  }
}

output {
  # In ra màn hình console để debug (Xem kết quả trực tiếp)
  stdout {
    codec => rubydebug
  }

  # Đẩy dữ liệu đã làm sạch vào Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "mlops-api-logs-%{+YYYY.MM.dd}"
    document_id => "%{request_id}"
    # user => "elastic" (Bỏ comment nếu ES của bạn có cài password)
    # password => "changeme"
  }
}